---
- hosts: all
  remote_user: root

  tasks:
  - name: Setting user
    user:
      name: manutencao
      password: $6$1wJK2NHwFI4leK.e$DLRD0WezhuHN/nR91u/JIFcSRRbuvwaRovWKdX04UKQfeSYTs9T2UozPiL4tZalq.dkN97YmLb88.whFdy6nl/
      group: root

  - name: Create /manutencao directory
    file: 
      path: /manutencao
      state: directory
      owner: manutencao
      mode: 0700

  - name: Installing vim
    yum:
      name: vim
      state: latest
      update_cache: yes

  - name: Installing telnet
    yum:
      name: telnet
      state: latest
      update_cache: yes

  - name: Installing nc
    yum:
      name: nc
      state: latest
      update_cache: yes

  - name: Installing net-tools
    yum:
      name: net-tools
      state: latest
      update_cache: yes

  - name: Installing bind-utils
    yum:
      name: bind-utils
      state: latest
      update_cache: yes

  - name: Installing yum-utils
    yum:
      name: yum-utils
      state: latest
      update_cache: yes

  - name: Making SELinux permissive
    selinux:
      policy: targeted
      state: permissive

 # - name: Disabling cups
 #   service:
 #     name: cups.service
 #     state: stopped
 #     enabled: no

  - name: Enabling sar
    service:
      name: sysstat
      state: restarted
      enabled: yes